create database hospital;
use hospital;
select* from hospital limit 5;
show tables;
RENAME TABLE cleaned_hospital_data TO hospital;

-- count total number of patients
select count(*) from hospital;
-- Find total revenue generated by the hospital.
select sum(revenue) from hospital;

-- List unique departments.
select distinct(department) from hospital;

-- Find average patient age.
select avg(age) from hospital;

-- Count patients in each department. 
select department, count(*)as patients  from hospital group by department;

-- Calculate total revenue by department.
select department ,sum(revenue) as total_revenue from hospital group by department;

-- Find average stay_days per department.
select department,avg(stay_days) from hospital group by department;

-- Count patients by gender.
select gender,count(*) from hospital group by gender;

-- Find number of patients from each city (descending order).
select city,count(*) from hospital group by city order by count(*) desc;

-- Find maximum revenue generated by a single patient.
select patient_id, sum(revenue) from hospital group by patient_id order by sum(revenue) desc limit 1;

-- Find top 5 highest bills (patients with highest Revenue).
select patient_id,sum(revenue) from hospital group by patient_id order by sum(revenue) desc limit 5;

-- Find department with highest revenue.
select department,sum(revenue) as highest_revenue from hospital group by department  order by sum(revenue) desc limit 1 ;

-- Find doctor who treated most patients.
select doctor_id,count(*) from hospital group by doctor_id order by count(*) desc limit 1;

-- Find top 5 doctors by revenue.
select doctor_id ,sum(revenue) from hospital group by doctor_id order by sum(revenue) desc limit 5;

-- Calculate monthly revenue trend.
select month,sum(revenue) from  hospital group by month ;

-- Find average stay_days by month.
select month,avg(stay_days) from hospital group by month;

-- Find total revenue for each city.
select city,sum(revenue) from hospital group by city;
-- Find number of patients admitted in each month.
select month,count(*) from hospital group by month;

-- Find departments where average stay_days > overall average stay.
SELECT department, AVG(stay_days) AS avg_stay
FROM hospital
GROUP BY department
HAVING AVG(stay_days) > (
    SELECT AVG(stay_days)
    FROM hospital
);	


